In [2]:
#Indlæser data
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df=pd.read_csv('dataset_diabetes/diabetic_data.csv', na_values = '?')
df.head()

C:\Users\katri\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [4]:
# Print percent of missing values in each column
miss_val = df.isna().sum()/df.shape[0]*100
print(round(miss_val, 2))

encounter_id                 0.00
patient_nbr                  0.00
race                         2.23
gender                       0.00
age                          0.00
weight                      96.86
admission_type_id            0.00
discharge_disposition_id     0.00
admission_source_id          0.00
time_in_hospital             0.00
payer_code                  39.56
medical_specialty           49.08
num_lab_procedures           0.00
num_procedures               0.00
num_medications              0.00
number_outpatient            0.00
number_emergency             0.00
number_inpatient             0.00
diag_1                       0.02
diag_2                       0.35
diag_3                       1.40
number_diagnoses             0.00
max_glu_serum                0.00
A1Cresult                    0.00
metformin                    0.00
repaglinide                  0.00
nateglinide                  0.00
chlorpropamide               0.00
glimepiride                  0.00
acetohexamide                0.00
glipizide                    0.00
glyburide                    0.00
tolbutamide                  0.00
pioglitazone                 0.00
rosiglitazone                0.00
acarbose                     0.00
miglitol                     0.00
troglitazone                 0.00
tolazamide                   0.00
examide                      0.00
citoglipton                  0.00
insulin                      0.00
glyburide-metformin          0.00
glipizide-metformin          0.00
glimepiride-pioglitazone     0.00
metformin-rosiglitazone      0.00
metformin-pioglitazone       0.00
change                       0.00
diabetesMed                  0.00
readmitted                   0.00
dtype: float64

In [5]:
# identify patients that occur mulitple times and remove the rows after
df_sort = df.sort_values('patient_nbr', inplace = False)
df_dropped = df_sort.drop_duplicates(subset = 'patient_nbr', keep='first', inplace=False)

df_dropped.shape

(71518, 50)

In [6]:
df['discharge_disposition_id'].dtypes

dtype('int64')

In [7]:
#removing patients who have died or are expectec to die within 30 days (hospice)
discharget_to_remove = [11, 13, 14, 19, 20, 21]  #all the ways to die...
indexNames = []
for i in discharget_to_remove:
    curindex = []
    curindex = df_dropped[ df_dropped['discharge_disposition_id'] == i].index
    indexNames.extend(curindex) 
df_minus_dead = df_dropped.drop(indexNames, inplace=False)
print("indexNames: ", len(indexNames))
print(df_minus_dead.shape)

indexNames:  1857
(69661, 50)

In [8]:
#Dropping features with a lot of missing values
df_dropped_columns=df_minus_dead.drop(['weight','payer_code'], axis=1)
print(df_dropped_columns.shape)

(69661, 48)

In [13]:
df_dropped_columns.to_csv(path_or_buf = 'dataset_diabetes/Reshaped_dataframe.csv', index = False)

In [14]:
df_dropped_columns.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
4267,24437208,135,Caucasian,Female,[50-60),2,1,1,8,Cardiology,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
5827,29758806,378,Caucasian,Female,[50-60),3,1,1,2,Surgery-Neuro,...,No,No,No,No,No,No,No,No,No,NO
67608,189899286,729,Caucasian,Female,[80-90),1,3,7,4,InternalMedicine,...,No,No,No,No,No,No,No,No,Yes,NO
17494,64331490,774,Caucasian,Female,[80-90),1,1,7,3,InternalMedicine,...,No,No,No,No,No,No,No,Ch,Yes,NO
2270,14824206,927,AfricanAmerican,Female,[30-40),1,1,7,5,InternalMedicine,...,No,No,No,No,No,No,No,No,Yes,NO